---
title: 'a few cool color palettes'
author: 'shelby bachman'
output: html_document
html_document:
  theme: flatly
  highlight: default
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = FALSE,
                      warnings = FALSE,
                      message = FALSE,
                      fig.align = 'left')

library(scales)
library(ggplot2)
library(ggpubr)

```

```{r palette_1_show, fig.width = 8}

palette_1 <- c('#ED6A5A', '#E5DF61', '#9BC1BC', '#5D576B')

data <- data.frame(
  num = c(1,1,1,1),
  order = c(1,2,3,4),
  col = palette_1
)
data$col <- factor(data$col, levels = palette_1)

ggplot(data, aes(x = reorder(col, order), y = num)) +
  geom_point(aes(colour = col), size = 60) +
  geom_text(aes(label = col), colour = 'black', family = 'Lato', size = 6) +
  scale_colour_manual(values = palette_1) +
  guides(colour = FALSE) +
  labs(x = '', y = '') +
  theme_pubr() +
  theme(axis.text = element_blank(),
        axis.ticks = element_blank(),
        axis.line = element_blank())

```

<details><summary>code</summary>

```{r palette_1_code, echo = TRUE, eval = FALSE}

c('#ED6A5A', '#E5DF61', '#9BC1BC', '#5D576B')

```

</details>

```{r palette_2_show, fig.width = 10}

palette_2 <- c('#667761', '#545E56', '#917C78', '#B79492', '#EAE1DF')

data <- data.frame(
  num = c(1,1,1,1,1),
  order = c(1,2,3,4,5),
  col = palette_2
)
data$col <- factor(data$col, levels = palette_2)

ggplot(data, aes(x = reorder(col, order), y = num)) +
  geom_point(aes(colour = col), size = 60) +
  geom_text(aes(label = col), colour = 'black', family = 'Lato', size = 6) +
  scale_colour_manual(values = palette_2) +
  guides(colour = FALSE) +
  labs(x = '', y = '') +
  theme_pubr() +
  theme(axis.text = element_blank(),
        axis.ticks = element_blank(),
        axis.line = element_blank())

```

<details><summary>code</summary>

```{r palette_2_code, echo = TRUE, eval = FALSE}

c('#667761', '#545E56', '#917C78', '#B79492', '#EAE1DF')

```

</details>

```{r palette_3_show, fig.width = 12}

palette_3 <- c('#D5573B', '#885053', '#777DA7', '#94C9A9', '#C6ECAE', '#EAE151')

data <- data.frame(
  num = c(1,1,1,1,1,1),
  order = c(1,2,3,4,5,6),
  col = palette_3
)
data$col <- factor(data$col, levels = palette_3)

ggplot(data, aes(x = reorder(col, order), y = num)) +
  geom_point(aes(colour = col), size = 60) +
  geom_text(aes(label = col), colour = 'black', family = 'Lato', size = 6) +
  scale_colour_manual(values = palette_3) +
  guides(colour = FALSE) +
  labs(x = '', y = '') +
  theme_pubr() +
  theme(axis.text = element_blank(),
        axis.ticks = element_blank(),
        axis.line = element_blank())

```

<details><summary>code</summary>

```{r palette_3_code, echo = TRUE, eval = FALSE}

palette_3 <- c('#D5573B', '#885053', '#777DA7', '#94C9A9', '#C6ECAE', '#EAE151')

```

</details>